version: '3.8'
services:
  mongodb:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mcp_users
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
